# Get a list of the dimensions used by the harmonised dataset

PREFIX qb: <http://purl.org/linked-data/cube#>

SELECT DISTINCT ?dimension 
FROM __RELEASE__
WHERE {
	?dsd a qb:DataStructureDefinition.
	?dsd qb:component [ qb:dimension ?dimension ].
}