PREFIX tablink: <http://bit.ly/cedar-tablink#>

SELECT DISTINCT ?cell ?literal ?header_type ?dataset_name
FROM __RAW_DATA__ 
WHERE {
	?cell a ?header_type.
	?cell tablink:value ?literal.
	?cell tablink:sheet __DATA_SET__. 
	?dataset dcterms:hasPart __DATA_SET__.
	?dataset rdfs:label ?dataset_name.
	FILTER (?header_type IN (tablink:RowHeader,tablink:ColumnHeader))
	FILTER (?literal != "")
} 
